-- PostgreSQL-family desired state for Embedded Alerts semantic embeddings.
-- Runtime processes must never apply this file at startup; migration tooling owns it.

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;
CREATE SCHEMA IF NOT EXISTS embedded_alerts;

CREATE OR REPLACE FUNCTION embedded_alerts.pad_embedding_4100(input_values real[])
RETURNS extensions.vector(4100)
LANGUAGE plpgsql
IMMUTABLE
STRICT
AS $$
DECLARE
  source_dimensions integer := array_length(input_values, 1);
  padded real[];
BEGIN
  IF source_dimensions IS NULL OR source_dimensions < 1 OR source_dimensions > 4096 THEN
    RAISE EXCEPTION 'embedding source dimensions must be between 1 and 4096';
  END IF;
  IF EXISTS (
    SELECT 1 FROM unnest(input_values) AS value
    WHERE value::text IN ('NaN', 'Infinity', '-Infinity')
  ) THEN
    RAISE EXCEPTION 'embedding values must be finite';
  END IF;
  padded := input_values || array_fill(0.0::real, ARRAY[4100 - source_dimensions]);
  RETURN padded::extensions.vector(4100);
END
$$;

CREATE OR REPLACE FUNCTION embedded_alerts.embedding_has_zero_tail(
  input_embedding extensions.vector(4100),
  original_dimensions integer
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
  SELECT original_dimensions BETWEEN 1 AND 4096
     AND extensions.l2_norm(
       extensions.subvector(input_embedding, original_dimensions + 1, 4100 - original_dimensions)
     ) = 0;
$$;

CREATE TABLE IF NOT EXISTS embedded_alerts.semantic_embeddings (
  embedding_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL,
  entity_kind text NOT NULL,
  entity_id text NOT NULL,
  purpose text NOT NULL,
  embedding_provider text NOT NULL,
  model text NOT NULL,
  original_dimensions integer NOT NULL CHECK (original_dimensions BETWEEN 1 AND 4096),
  embedding extensions.vector(4100) NOT NULL,
  normalization text NOT NULL,
  content_hash text NOT NULL,
  search_text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT semantic_embeddings_zero_tail CHECK (
    embedded_alerts.embedding_has_zero_tail(embedding, original_dimensions)
  ),
  CONSTRAINT semantic_embeddings_identity UNIQUE (
    tenant_id, entity_kind, entity_id, purpose, embedding_provider, model, content_hash
  )
);

-- ANN is intentionally separate from the exact 4100-value authority. pgvector's
-- halfvec HNSW ceiling is 4000 dimensions, so the exact table carries no ANN index.
CREATE TABLE IF NOT EXISTS embedded_alerts.semantic_embedding_index (
  embedding_id bigint PRIMARY KEY
    REFERENCES embedded_alerts.semantic_embeddings(embedding_id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL,
  purpose text NOT NULL,
  embedding_space text NOT NULL,
  indexed_embedding extensions.halfvec(4000) NOT NULL
);

CREATE INDEX IF NOT EXISTS semantic_embedding_index_tenant_space_purpose
  ON embedded_alerts.semantic_embedding_index (tenant_id, embedding_space, purpose);

CREATE INDEX IF NOT EXISTS semantic_embedding_index_hnsw
  ON embedded_alerts.semantic_embedding_index
  USING hnsw (indexed_embedding extensions.halfvec_cosine_ops);

CREATE OR REPLACE FUNCTION embedded_alerts.sync_semantic_embedding_index()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO embedded_alerts.semantic_embedding_index (
    embedding_id,
    tenant_id,
    purpose,
    embedding_space,
    indexed_embedding
  ) VALUES (
    NEW.embedding_id,
    NEW.tenant_id,
    NEW.purpose,
    NEW.embedding_provider || ':' || NEW.model || ':' || NEW.original_dimensions::text || ':' || NEW.normalization,
    extensions.subvector(NEW.embedding, 1, 4000)::extensions.halfvec(4000)
  )
  ON CONFLICT (embedding_id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    purpose = EXCLUDED.purpose,
    embedding_space = EXCLUDED.embedding_space,
    indexed_embedding = EXCLUDED.indexed_embedding;
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS semantic_embeddings_sync_ann ON embedded_alerts.semantic_embeddings;
CREATE TRIGGER semantic_embeddings_sync_ann
AFTER INSERT OR UPDATE OF tenant_id, purpose, embedding_provider, model,
  original_dimensions, embedding, normalization
ON embedded_alerts.semantic_embeddings
FOR EACH ROW EXECUTE FUNCTION embedded_alerts.sync_semantic_embedding_index();

ALTER TABLE embedded_alerts.semantic_embeddings ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'embedded_alerts'
      AND tablename = 'semantic_embeddings'
      AND policyname = 'semantic_embeddings_tenant'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY semantic_embeddings_tenant
      ON embedded_alerts.semantic_embeddings
      FOR SELECT TO vector_contract_app
      USING (
        tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
      )
    $policy$;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'embedded_alerts'
      AND tablename = 'semantic_embeddings'
      AND policyname = 'semantic_embeddings_service_role'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY semantic_embeddings_service_role
      ON embedded_alerts.semantic_embeddings
      FOR SELECT TO service_role
      USING (true)
    $policy$;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA embedded_alerts, extensions TO vector_contract_app, service_role;
GRANT SELECT ON embedded_alerts.semantic_embeddings TO vector_contract_app, service_role;
GRANT SELECT ON embedded_alerts.semantic_embedding_index TO vector_contract_app, service_role;
